font_names = [
    "ADTNumeric.ttc",
    "Apple Color Emoji.ttc",
    "Apple Symbols.ttf",
    "AppleSDGothicNeo.ttc",
    "AquaKana.ttc",
    "Arial Unicode.ttf",
    "ArialHB.ttc",
    "Avenir Next Condensed.ttc",
    "Avenir Next.ttc",
    "Avenir.ttc",
    "Courier.ttc",
    "GeezaPro.ttc",
    "Geneva.ttf",
    "HelveLTMM",
    "Helvetica.ttc",
    "HelveticaNeue.ttc",
    "Hiragino Sans GB.ttc",
    "Keyboard.ttf",
    "Kohinoor.ttc",
    "KohinoorBangla.ttc",
    "KohinoorGujarati.ttc",
    "KohinoorTelugu.ttc",
    "LastResort.otf",
    "LucidaGrande.ttc",
    "MarkerFelt.ttc",
    "Menlo.ttc",
    "Monaco.ttf",
    "MuktaMahee.ttc",
    "NewYork.ttf",
    "NewYorkItalic.ttf",
    "Noteworthy.ttc",
    "NotoNastaliq.ttc",
    "NotoSansArmenian.ttc",
    "NotoSansKannada.ttc",
    "NotoSansMyanmar.ttc",
    "NotoSansOriya.ttc",
    "NotoSerifMyanmar.ttc",
    "Optima.ttc",
    "Palatino.ttc",
    "PingFang.ttc",
    "SFArabic.ttf",
    "SFArabicRounded.ttf",
    "SFArmenian.ttf",
    "SFArmenianRounded.ttf",
    "SFCamera.ttf",
    "SFCompact.ttf",
    "SFCompactItalic.ttf",
    "SFCompactRounded.ttf",
    "SFGeorgian.ttf",
    "SFGeorgianRounded.ttf",
    "SFNS.ttf",
    "SFNSItalic.ttf",
    "SFNSMono.ttf",
    "SFNSMonoItalic.ttf",
    "SFNSRounded.ttf",
    "STHeiti Light.ttc",
    "STHeiti Medium.ttc",
    "Supplemental",
    "Symbol.ttf",
    "ThonburiUI.ttc",
    "Times.ttc",
    "TimesLTMM",
    "ZapfDingbats.ttf",
]
